services:
  - type: web
    name: blogging-service
    env: go
    buildCommand: ./render-build.sh
    startCommand: ./server
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: blog-postgres
          property: connectionString
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: blogapp
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: ""

databases:
  - name: blog-postgres
    plan: free
